name: ccc-dev
channels:
- PSLmodels
- conda-forge
dependencies:
- python=3.6
- taxcalc
- setuptools
- scipy
- xlrd
- pytest
- pytest-pep8
- pytest-xdist
- mock
- pycodestyle
- pylint
- coverage
- paramtools